blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/ant-design/ant-design-mobile/discussions
    about: Ask questions and discuss with other community members
