name: General Issue
description: Open a blank issue
body:
  - type: input
    id: antd-mobile-version
    attributes:
      label: Version of antd-mobile
      description: |
        The exact version of antd-mobile you are using.
        你所使用的 antd-mobile 的准确版本。
      placeholder: eg. 5.7.2
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Please tell us about your idea in as much detail as possible.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/ant-design/ant-design-mobile/blob/master/.github/CODE_OF_CONDUCT.md)
