name: Close Inactive Pending Issues

on:
  schedule:
    - cron: '30 23 * * *' # At 23:30 UTC every day

jobs:
  check-need-info:
    runs-on: ubuntu-latest
    steps:
      - name: close-issues
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issues'
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'pending'
          inactive-day: 7
          body: |
            This issue will be closed automatically due to being inactive for a long time.

            由于较长时间没有更新，此 issue 将自动关闭。
